"""
ArenaEnumMappings.cs 自動生成スクリプト

arena.data の Enum 定義から C# の ArenaEnumMappings.cs を生成する。
ArenaQuestManager.cs から参照して使用する。
"""

import os
import sys
from enum import Enum
from typing import Type, List, Tuple

# パス設定
BUILDER_DIR = os.path.dirname(os.path.abspath(__file__))
TOOLS_DIR = os.path.dirname(BUILDER_DIR)
PROJECT_ROOT = os.path.dirname(TOOLS_DIR)
sys.path.insert(0, TOOLS_DIR)

# arena パッケージからインポート
from arena.data import (
    Rank,
    Phase,
    BalgasChoice,
    BottleChoice,
    KainSoulChoice,
    LilyBottleConfession,
    Ending,
    Keys,
    PREFIX,
)

OUTPUT_PATH = os.path.join(PROJECT_ROOT, "src", "Generated", "ArenaEnumMappings.cs")


# Enum とフラグキーのマッピング
ENUM_FLAG_MAPPINGS: List[Tuple[Type[Enum], str]] = [
    (Rank, Keys.RANK),
    (Phase, Keys.CURRENT_PHASE),
    (BalgasChoice, Keys.BALGAS_KILLED),
    (BottleChoice, Keys.BOTTLE_CHOICE),
    (KainSoulChoice, Keys.KAIN_SOUL_CHOICE),
    (LilyBottleConfession, Keys.LILY_BOTTLE_CONFESSION),
    (Ending, Keys.ENDING),
]


def generate_enum_mappings():
    """ArenaEnumMappings.cs を生成"""

    code = """// <auto-generated>
// This file is auto-generated by generate_enum_mappings.py
// Do not edit manually. Changes will be overwritten on next build.
// </auto-generated>

using System.Collections.Generic;

namespace Elin_SukutsuArena
{
    /// <summary>
    /// フラグキーとEnum値のマッピング（自動生成）
    /// </summary>
    public static class ArenaEnumMappings
    {
        /// <summary>
        /// フラグキー → (文字列値 → 整数値) のマッピング
        /// </summary>
        public static readonly Dictionary<string, Dictionary<string, int>> Mappings =
            new Dictionary<string, Dictionary<string, int>>
        {
"""

    # 各Enumのマッピングを生成
    for enum_type, flag_key in ENUM_FLAG_MAPPINGS:
        code += f"            {{\n"
        code += f'                "{flag_key}", new Dictionary<string, int>\n'
        code += f"                {{\n"

        # Enum値を順番に追加
        for i, member in enumerate(enum_type):
            code += f'                    {{ "{member.value}", {i} }},\n'

        code += f"                }}\n"
        code += f"            }},\n"

    code += """        };
    }
}
"""

    # ファイルに書き込み
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(code)

    print(f"Generated: {OUTPUT_PATH}")
    print(f"  - {len(ENUM_FLAG_MAPPINGS)} enum mappings")
    for enum_type, flag_key in ENUM_FLAG_MAPPINGS:
        print(f"    - {flag_key}: {len(list(enum_type))} values")


if __name__ == "__main__":
    generate_enum_mappings()
