"""
JumpLabelMapping.cs 自動生成スクリプト

flag_definitions.py の JUMP_LABELS から C# の JumpLabelMapping.cs を生成する。
"""

import os
import sys
import re
from collections import defaultdict

# パス設定
BUILDER_DIR = os.path.dirname(os.path.abspath(__file__))
TOOLS_DIR = os.path.dirname(BUILDER_DIR)
PROJECT_ROOT = os.path.dirname(TOOLS_DIR)

# arena パッケージをパスに追加
sys.path.insert(0, TOOLS_DIR)

from arena.data import JUMP_LABELS

OUTPUT_PATH = os.path.join(PROJECT_ROOT, "src", "Generated", "JumpLabelMapping.cs")


def snake_to_pascal(name: str) -> str:
    """snake_case を PascalCase に変換"""
    return "".join(word.capitalize() for word in name.split("_"))


def generate_enum_name(label: str) -> str:
    """ラベル名から enum 名を生成"""
    return snake_to_pascal(label)


def generate_jump_label_mapping():
    """JumpLabelMapping.cs を生成"""

    # 値でグループ化（同じ値を持つラベルを集約）
    value_to_labels = defaultdict(list)
    for label, value in JUMP_LABELS.items():
        value_to_labels[value].append(label)

    # enum メンバーを生成（各値に対して代表的な名前を選択）
    enum_members = []
    enum_members.append(("None", 0))

    for value in sorted(value_to_labels.keys()):
        labels = value_to_labels[value]
        # start_ プレフィックスを優先、なければ最初のラベルを使用
        primary_label = None
        for label in labels:
            if label.startswith("start_"):
                primary_label = label
                break
        if primary_label is None:
            primary_label = labels[0]

        enum_name = generate_enum_name(primary_label)
        enum_members.append((enum_name, value))

    # マッピングを生成
    label_mappings = []
    for label, value in sorted(JUMP_LABELS.items()):
        # この値に対応する enum 名を見つける
        labels_for_value = value_to_labels[value]
        primary_label = None
        for l in labels_for_value:
            if l.startswith("start_"):
                primary_label = l
                break
        if primary_label is None:
            primary_label = labels_for_value[0]

        enum_name = generate_enum_name(primary_label)
        label_mappings.append((label, enum_name))

    # C# コードを生成
    code = """// <auto-generated>
// This file is auto-generated by generate_jump_label_mapping.py
// Do not edit manually. Changes will be overwritten on next build.
// </auto-generated>

using System.Collections.Generic;

namespace Elin_SukutsuArena.Data
{
    /// <summary>
    /// ドラマスクリプトのジャンプラベル
    /// </summary>
    public enum JumpLabel
    {
"""

    # enum メンバーを追加
    for enum_name, value in enum_members:
        code += f"        {enum_name} = {value},\n"

    code += """    }

    /// <summary>
    /// 文字列ラベルとJumpLabel enumのマッピング
    /// </summary>
    public static class JumpLabelMapping
    {
        private static readonly Dictionary<string, JumpLabel> _labelToEnum = new Dictionary<string, JumpLabel>
        {
"""

    # マッピングを追加
    for label, enum_name in label_mappings:
        code += f'            ["{label}"] = JumpLabel.{enum_name},\n'

    code += """        };

        /// <summary>
        /// 文字列ラベルからJumpLabel enumに変換
        /// </summary>
        public static JumpLabel FromString(string label)
        {
            if (string.IsNullOrEmpty(label)) return JumpLabel.None;
            return _labelToEnum.TryGetValue(label, out var result) ? result : JumpLabel.None;
        }
    }
}
"""

    # ファイルに書き込み
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(code)

    print(f"Generated: {OUTPUT_PATH}")
    print(f"  - {len(enum_members)} enum members")
    print(f"  - {len(label_mappings)} label mappings")


if __name__ == "__main__":
    generate_jump_label_mapping()
